name: gallery_saver_example
description: Demonstrates how to use the gallery_saver plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  image_picker: ^0.6.3+1
  path_provider: ^1.6.0
  http: ^0.12.0+4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  gallery_saver:
    path: ../

flutter:
  uses-material-design: true
